version: "3.8"
services:
  mysql:
    image: 'mysql'
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    env_file:
      - ./mysql_docker/mysql.env
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "${MYSQL_ROOT_USERNAME-root}", "--password=${MYSQL_ROOT_PASSWORD-root}}" ]
      timeout: 5s
      retries: 10
  backend:
    build: .
    ports:
      - '8080:8080'
    volumes:
      - logs:/opt/pancakes_unlimited/logs
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql-data:
  logs: