version: "2.1"
services:
  mysql:
    image: 'mysql'
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    cap_add:
      - SYS_NICE
    security_opt:
      - seccomp:unconfined
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pancakes_unlimited_db
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "--password=root}" ]
      timeout: 10s
      retries: 5
  backend:
    build: .
    ports:
      - '8080:8080'
    volumes:
      - logs:/opt/pancakes_unlimited/logs
    env_file:
      - .env
    security_opt:
      - seccomp:unconfined
    depends_on:
      mysql:
        condition: service_healthy
#    links:
#      - mysqldb

volumes:
  mysql-data:
  logs: