version: "3.8"

#used for testing
services:

  mysql-development:
    image: mysql:8.0.28
    container_name: mysql
    ports:
      - "3308:3306"
    env_file:
      - ./mysql.env
#    volumes:
#      - mysql_db:/var/lib/mysql

#volumes:
#  mysql_db:
