version: "3.8"

services:

  mysql-development:
    image: mysql:8.0.28
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pancakes_unlimited_db
    volumes:
      - mysql_db:/var/lib/mysql
    ports:
      - "3308:3306"

volumes:
  mysql_db:
